### ISSUE TITLE
请问bilibili的视频地址在哪啊？想看下哈。

### ISSUE THREAD

**Issue by welkinchan** [jackwuwei/gptspeaker#2]

**Comment by jackwuwei** [comment]
https://www.bilibili.com/video/BV1Wo4y1K7dW/?spm_id_from=333.999.0.0&vd_source=c162ca324705ef3601553e2531436616

**Comment by welkinchan** [comment]
> 这个是[演示视频地址](https://www.bilibili.com/video/BV1Wo4y1K7dW/?spm_id_from=333.999.0.0&vd_source=c162ca324705ef3601553e2531436616)，另外还有一个[增强版](https://www.bilibili.com/video/BV14j411r73M/?spm_id_from=333.999.0.0)的，还没有开源

我看了下2个视频，2款性能的响应延迟相差好大啊。增强版的响应延时好短，是用了离线的whisper吗？另外，智能方面是不是也用了langchain的方案？感觉好强啊，居然流量这么小。增强版有开源的计划吗？好想试试看。

**Comment by welkinchan** [comment]
> > > 这个是[演示视频地址](https://www.bilibili.com/video/BV1Wo4y1K7dW/?spm_id_from=333.999.0.0&vd_source=c162ca324705ef3601553e2531436616)，另外还有一个[增强版](https://www.bilibili.com/video/BV14j411r73M/?spm_id_from=333.999.0.0)的，还没有开源
> > 
> > 
> > 我看了下2个视频，2款性能的响应延迟相差好大啊。增强版的响应延时好短，是用了离线的whisper吗？另外，智能方面是不是也用了langchain的方案？感觉好强啊，居然流量这么小。增强版有开源的计划吗？好想试试看。
> 
> 1. 增强版的延时也比较大，视频经过了剪辑，改为Azure中国可能会好一些，本地部署Whisper也可行，但需要比较强的硬件
> 2. 智能方面没有用langchain，用的是GPT function calling，langchain会更成熟一些，也是基于function calling实现的
> 3. 增强版的代码还需要优化，等有时间优化好了才能开源

我想先进一步了解下目前已经开源的这部分代码。
我成功运行起来后发现，
怎么感觉这部分的代码的语音响应时间比第一个bilibili视频里的响应时间要快很多啊。
而且，目前的代码是不能连续对话的，每次都要唤醒，跟你的视频里的表现也不一样。哈哈。

**Comment by jackwuwei** [comment]
> > > > 这个是[演示视频地址](https://www.bilibili.com/video/BV1Wo4y1K7dW/?spm_id_from=333.999.0.0&vd_source=c162ca324705ef3601553e2531436616)，另外还有一个[增强版](https://www.bilibili.com/video/BV14j411r73M/?spm_id_from=333.999.0.0)的，还没有开源
> > > 
> > > 
> > > 我看了下2个视频，2款性能的响应延迟相差好大啊。增强版的响应延时好短，是用了离线的whisper吗？另外，智能方面是不是也用了langchain的方案？感觉好强啊，居然流量这么小。增强版有开源的计划吗？好想试试看。
> > 
> > 
> > 
> > 1. 增强版的延时也比较大，视频经过了剪辑，改为Azure中国可能会好一些，本地部署Whisper也可行，但需要比较强的硬件
> > 2. 智能方面没有用langchain，用的是GPT function calling，langchain会更成熟一些，也是基于function calling实现的
> > 3. 增强版的代码还需要优化，等有时间优化好了才能开源
> 
> 我想先进一步了解下目前已经开源的这部分代码。 我成功运行起来后发现， 怎么感觉这部分的代码的语音响应时间比第一个bilibili视频里的响应时间要快很多啊。 而且，目前的代码是不能连续对话的，每次都要唤醒，跟你的视频里的表现也不一样。哈哈。

1. B站的演示视频是在树莓派上运行的，速度比电脑上要慢一些
2. 这里的连续对话是指能记住上下文对话，如果不想每次唤醒可以修改代码做到，但体验并不好，视频里是经过剪辑的，剪掉了唤醒词
