### ISSUE TITLE
Integrating Azure Open AI instead of ChatGPT?

### ISSUE THREAD

**Issue by tarunaroraonline** [jackwuwei/gptspeaker#6]
I was wondering if it would be possible to get Azure Open AI integrated to form the responses rather than using ChatGPT?

**Comment by jackwuwei** [comment]
> I was wondering if it would be possible to get Azure Open AI integrated to form the responses rather than using ChatGPT?

Yes, you can use Azure OpenAI API instead of ChatGPT. I will commit the relevant code later.

**Comment by tarunaroraonline** [comment]
Ok i've added that capability, i'll raise a pull request for your review.

**Comment by jackwuwei** [comment]
> Ok i've added that capability, i'll raise a pull request for your review.

Thanks! I've added support for Azure OpenAI, please pull source code.
